server:
   port: 8085
   servlet:
      context-path: /angular
spring:
   application:
      name: ANGULAR-BACKEND
   mail:
      host: "smtp.gmail.com"
      port: 587
      username: "hainnovate121@gmail.com"
      password: "hainnovate@143"
      properties:
         mail:
            smtp:
               auth: true
               starttls:
                  enable: true
   jpa:
      show-sql: true
      properties:
         hibernate:
            format_sql: true
            jdbc:
              lob:
                non_contextual_creation: true
            default_schema: tutor_app      hibernate:        ddl-auto: update
      database-platform: org.hibernate.dialect.PostgreSQLDialect
   datasource:
      url: "jdbc:postgresql://localhost:5432/tutor_student" 
      username: tutorappuser
      password: tutoradmin
   h2:
      console:
         enabled: true
         path: /h2-console
      
logging:
   level:
      org:
         hibernate:
            SQL: DEBUG
            type:
               decriptor:
                  sql:
                     BasicBinder: TRACE
                   
         
            
application:
   security:
      key: "hafeezSecretOrg143123OgrfarmLucknow2019"
   api:
      url: "http://localhost:${server.port}${server.servlet.context-path}"

      
